/* =========================================================
 * 新幹線の窓 — 旅の瞬間を見逃さない / Shinkansen Window
 * data.js — 車窓スポットデータ（バイリンガル）
 *
 * minutesFromTokyo: のぞみ基準の東京発からの目安分数（東京→新大阪 約147分）
 * side: "E" = 山側（北側・E席） / "A" = 海側（南側・A席）
 *       東海道新幹線はどちら向きでもE席が山側になる
 * category: 内部の並び順ランク。画面表示タグは図鑑フィルタ（自然/歴史/工業/看板/街並）に揃える
 * confidence: "verified"（実見・写真あり） / "source-backed"（出典あり） / "needs-check"（裏取り中）
 * ========================================================= */

const ROUTE = {
  totalMinutes: 147, // のぞみ 東京→新大阪 目安
  // 全駅の「東京からの通過目安分数」(のぞみ速度基準・距離按分)。
  // 実ダイヤ接続時はこの値を使い、選択列車の停車駅時刻のあいだを線形補間する。
  refStations: [
    { id: "Tokyo", ja: "東京", en: "Tokyo", min: 0, major: true },
    { id: "Shinagawa", ja: "品川", en: "Shinagawa", min: 7, major: true },
    { id: "Shin-Yokohama", ja: "新横浜", en: "Shin-Yokohama", min: 18, major: true },
    { id: "Odawara", ja: "小田原", en: "Odawara", min: 31 },
    { id: "Atami", ja: "熱海", en: "Atami", min: 36 },
    { id: "Mishima", ja: "三島", en: "Mishima", min: 40 },
    { id: "Shin-Fuji", ja: "新富士", en: "Shin-Fuji", min: 45 },
    { id: "Shizuoka", ja: "静岡", en: "Shizuoka", min: 53 },
    { id: "Kakegawa", ja: "掛川", en: "Kakegawa", min: 64 },
    { id: "Hamamatsu", ja: "浜松", en: "Hamamatsu", min: 70 },
    { id: "Toyohashi", ja: "豊橋", en: "Toyohashi", min: 79 },
    { id: "Mikawa-Anjo", ja: "三河安城", en: "Mikawa-Anjo", min: 88 },
    { id: "Nagoya", ja: "名古屋", en: "Nagoya", min: 95, major: true },
    { id: "Gifu-Hashima", ja: "岐阜羽島", en: "Gifu-Hashima", min: 102 },
    { id: "Maibara", ja: "米原", en: "Maibara", min: 114 },
    { id: "Kyoto", ja: "京都", en: "Kyoto", min: 130, major: true },
    { id: "Shin-Osaka", ja: "新大阪", en: "Shin-Osaka", min: 147, major: true },
  ],
  get stations() { return this.refStations.filter((s) => s.major); },
};

const REFERENCES = {
  toyokeizaiWindow: {
    label: { ja: "東洋経済オンライン: 新幹線の車窓はこんなに面白い", en: "Toyo Keizai Online: Tokaido Shinkansen window views" },
    url: "https://toyokeizai.net/list/column/694384d86b208d3b9c000052",
  },
  toyokeizaiMikawa: {
    label: { ja: "東洋経済オンライン: 三河湾の車窓", en: "Toyo Keizai Online: Mikawa Bay window view" },
    url: "https://toyokeizai.net/articles/-/128329",
  },
  hinataokaRakumachi: {
    label: { ja: "楽待: 日向岡の住宅地", en: "Rakumachi: Hinataoka hillside homes (Japanese only)" },
    url: "https://www.rakumachi.jp/news/column/339459",
  },
  tokyoTowerBlog: {
    label: { ja: "@letus10: 東京タワー車窓記事", en: "@letus10: Tokyo Tower window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/507672955.html",
  },
  atami: {
    label: { ja: "Wikipedia: 熱海", en: "Wikipedia: Atami" },
    url: {
      ja: "https://ja.wikipedia.org/wiki/%E7%86%B1%E6%B5%B7",
      en: "https://en.wikipedia.org/wiki/Atami",
    },
  },
  hatsushimaBlog: {
    label: { ja: "@letus10: 初島車窓記事", en: "@letus10: Hatsushima window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/516720935.html",
  },
  atamiCastleBlog: {
    label: { ja: "@letus10: 熱海城車窓記事", en: "@letus10: Atami Castle window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/516721203.html",
  },
  weatherFuji: {
    label: { ja: "ウェザーニュース: 新幹線の富士山スポット", en: "Weathernews: Mt. Fuji from the Shinkansen" },
    url: {
      ja: "https://weathernews.jp/news/202604/240201/",
      en: "https://global.jr-central.co.jp/en/onlinebooking/featured-theme/mtfuji/",
    },
  },
  leftFujiTrafficNews: {
    label: { ja: "乗りものニュース: 左富士", en: "Traffic News: Left-side Fuji (Japanese only)" },
    url: "https://trafficnews.jp/post/62565",
  },
  odawaraCastle: {
    label: { ja: "小田原城公式", en: "Odawara Castle official site" },
    url: "https://odawaracastle.com/",
  },
  odawaraCastleBlog: {
    label: { ja: "@letus10: 小田原城車窓記事", en: "@letus10: Odawara Castle window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/516754194.html",
  },
  gyoranKannon: {
    label: { ja: "日本珍スポット100景: 魚籃観音", en: "Bqspot: Gyoran Kannon (Japanese only)" },
    url: "https://bqspot.com/kanto/kanagawa/440",
  },
  shimizuPort: {
    label: { ja: "清水港: 地球深部探査船「ちきゅう」", en: "Port of Shimizu: Deep-sea drilling vessel CHIKYU" },
    url: "https://www.portofshimizu.com/overview/%E5%9C%B0%E7%90%83%E6%B7%B1%E9%83%A8%E6%8E%A2%E6%9F%BB%E8%88%B9-%E3%81%A1%E3%81%8D%E3%82%85%E3%81%86/",
  },
  shizuokaTeaTourism: {
    label: { ja: "お茶のまち静岡市: 観光", en: "Ochanomachi Shizuoka City: Tourism" },
    url: "https://www.ochanomachi-shizuokashi.jp/tourism/",
  },
  kakegawaCastle: {
    label: { ja: "掛川城公式", en: "Kakegawa Castle official site" },
    url: "https://kakegawajo.com/",
  },
  genkiSignBlog: {
    label: { ja: "@letus10: 元気が出る看板車窓記事", en: "@letus10: Cheer-up signs window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/516019488.html",
  },
  genkiSignStreetView: {
    label: { ja: "Google マップ: 元気が出る看板付近", en: "Google Maps: Cheer-up signs area" },
    url: "https://www.google.com/maps/@34.7298265,137.8986674,3a,46.4y,18.58h,82.48t/data=!3m7!1e1!3m5!1sWkV2_8Z6dI0WHi46Bem_YA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D7.519999999999996%26panoid%3DWkV2_8Z6dI0WHi46Bem_YA%26yaw%3D18.58!7i16384!8i8192?entry=ttu",
  },
  hamanakoTourism: {
    label: { ja: "浜名湖観光圏", en: "Lake Hamana tourism" },
    url: {
      ja: "https://www.hamanako-tourism.com/",
      en: "https://hamanako-tourism.com/en/",
    },
  },
  hamanakoToriiBlog: {
    label: { ja: "@letus10: 浜名湖と弁天島鳥居の車窓記事", en: "@letus10: Lake Hamana and Bentenjima torii article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/517074141.html",
  },
  toyohashiTateiwa: {
    label: { ja: "デイリーポータルZ: 東海道本線の車窓から見える岩めぐり", en: "Daily Portal Z: Rocks visible from the Tokaido Line (Japanese only)" },
    url: "https://dailyportalz.jp/kiji/rocks-visible-from-Tokaido-Line",
  },
  kirinBlog: {
    label: { ja: "@letus10: キリンビール工場車窓記事", en: "@letus10: Kirin Beer Factory window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/518214924.html",
  },
  nichibanBlog: {
    label: { ja: "@letus10: セロテープの壁看板車窓記事", en: "@letus10: CELLOTAPE Wall Sign window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/510591087.html",
  },
  marukoBridgeBlog: {
    label: { ja: "@letus10: 丸子橋車窓記事", en: "@letus10: Maruko Bridge window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/515810649.html",
  },
  sevenTwoSevenNote: {
    label: { ja: "note: 727看板と新幹線の車窓", en: "note: 727 signs from the Shinkansen (Japanese only)" },
    url: "https://note.com/wotuntun/n/n3d2eceae1689",
  },
  sevenTwoSevenOfficial: {
    label: { ja: "727 セブンツーセブン化粧品", en: "727 Cosmetics official site" },
    url: "https://www.727.co.jp/",
  },
  kinshozanWiki: {
    label: { ja: "Wikipedia: 金生山", en: "Wikipedia: Mt. Kinsho (Japanese only)" },
    url: "https://ja.wikipedia.org/wiki/%E9%87%91%E7%94%9F%E5%B1%B1",
  },
  kiyosuCastle: {
    label: { ja: "清洲城", en: "Kiyosu Castle" },
    url: "http://kiyosujyo.com/",
  },
  gifuCastleBlog: {
    label: { ja: "@letus10: 岐阜城車窓記事", en: "@letus10: Gifu Castle window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/518296647.html",
  },
  solarArkBlog: {
    label: { ja: "@letus10: ソーラーアーク車窓記事", en: "@letus10: Solar Ark from the Shinkansen" },
    url: "https://cotetu.seesaa.net/article/519526266.html",
  },
  ibuki: {
    label: { ja: "Wikipedia: 伊吹山", en: "Japan Travel: Mt. Ibuki" },
    url: {
      ja: "https://ja.wikipedia.org/wiki/%E4%BC%8A%E5%90%B9%E5%B1%B1",
      en: "https://www.japan.travel/en/sports/hiking/courses/mt-ibuki/",
    },
  },
  kojodanWindowCastles: {
    label: { ja: "攻城団: 新幹線から見える城", en: "Kojodan: Castles visible from the Shinkansen" },
    url: "https://blog.kojodan.jp/entry/2019/03/10/130620",
  },
  nanguTaisha: {
    label: { ja: "南宮大社 公式", en: "Nangu Taisha official site" },
    url: "https://www.nangu-san.com/",
  },
  hikoneCastle: {
    label: { ja: "国宝 彦根城公式", en: "Hikone Castle official site" },
    url: "https://hikonecastle.com/",
  },
  sawayama: {
    label: { ja: "彦根観光ガイド: 佐和山城跡", en: "Hikone tourism: Sawayama Castle Ruins" },
    url: "https://www.hikoneshi.com/sightseeing/article/sawayama",
  },
  sawayamaBlog: {
    label: { ja: "@letus10: 佐和山城跡と彦根城の車窓記事", en: "@letus10: Sawayama and Hikone window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/517840979.html",
  },
  kannonjiCastle: {
    label: { ja: "Wikipedia: 観音寺城", en: "Wikipedia: Kannonji Castle" },
    url: {
      ja: "https://ja.wikipedia.org/wiki/%E8%A6%B3%E9%9F%B3%E5%AF%BA%E5%9F%8E",
      en: "https://en.wikipedia.org/wiki/Kannonji_Castle",
    },
  },
  omiFujiPark: {
    label: { ja: "Wikipedia: 三上山", en: "Wikipedia: Mount Mikami" },
    url: {
      ja: "https://ja.wikipedia.org/wiki/%E4%B8%89%E4%B8%8A%E5%B1%B1",
      en: "https://en.wikipedia.org/wiki/Mount_Mikami",
    },
  },
  setaKarahashi: {
    label: { ja: "@letus10: 瀬田の唐橋車窓記事", en: "@letus10: Seta no Karahashi window article (Japanese only)" },
    url: "https://cotetu.seesaa.net/article/517709224.html",
  },
  toji: {
    label: { ja: "THE THOUSAND KYOTO: 東寺", en: "THE THOUSAND KYOTO: To-ji Temple" },
    url: "https://www.keihanhotels-resorts.co.jp/the-thousand-kyoto/sight/kyoto-kawaramachi/touji.html",
  },
  tokaidoShinkansen: {
    label: { ja: "鉄道チャンネル: 鳥飼車両基地", en: "Tetsudo Channel: Torikai Train Depot (Japanese only)" },
    url: "https://tetsudo-ch.com/12903111.html",
  },
};

const SPOTS = [
  {
    id: "tokyo-tower",
    icon: "🗼",
    ja: { name: "東京タワー", area: "東京 → 品川", hook: "東京の空に、赤い塔。", story: "東京駅を出て品川へ向かう数分のあいだ、E席側のビルの間に東京タワーが見えます。旅の序盤、都市の景色の中に赤い塔がちらりと立つ。見えたら、東海道新幹線の車窓が始まった合図です。" },
    en: { name: "Tokyo Tower", area: "Tokyo → Shinagawa", hook: "A red tower in the Tokyo skyline.", story: "In the first few minutes after leaving Tokyo Station for Shinagawa, Tokyo Tower slips between the buildings on the Seat E side. It is a quick urban opening shot: the red tower appears, and the Tokaido Shinkansen window story begins." },
    minutesFromTokyo: 3, side: "E", category: "classic", confidence: "verified", durationSec: 35, scene: "hills",
    image: "images/20250111_tokyo_tower_letus10.jpg",
    photoCredit: {
      ja: "@letus10 / 新幹線の車窓から",
      en: "@letus10 / Shinkansen window blog",
      url: "https://cotetu.seesaa.net/article/507672955.html",
      note: { ja: "ビルの合間に見える東京タワー", en: "Tokyo Tower between the buildings" },
    },
    photos: [
      {
        src: "images/20260629_tokyo_tower_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見える東京タワー", en: "Tokyo Tower at night from the Shinkansen" },
        date: "2026-06-29",
        note: { ja: "夜の街に、東京タワー", en: "Tokyo Tower in the night city" },
      },
      {
        src: "images/20260629_tokyo_tower_night_2_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜のビルの合間に見える東京タワー", en: "Tokyo Tower between buildings at night" },
        date: "2026-06-29",
        note: { ja: "ビルの合間に光る塔", en: "A lit tower between buildings" },
      },
    ],
    references: [REFERENCES.tokyoTowerBlog],
    map: { lat: 35.65858, lng: 139.74543, ja: "東京タワー", en: "Tokyo Tower" },
  },
  {
    id: "hinataoka",
    icon: "🏘️",
    ja: { name: "日向岡の街並み", area: "新横浜 → 小田原", hook: "斜面いっぱいに、おなじ屋根がならぶ。", story: "相模川を渡ってしばらくすると、丘の斜面にそろって並ぶ住宅地が一瞬あらわれます。名所ではありません。でも、知っている人だけが「あ、来た」と窓の外を見る——そういう車窓です。" },
    en: { name: "Hinataoka Hillside Homes", area: "Shin-Yokohama → Odawara", hook: "Matching rooftops on a hillside.", story: "Shortly after crossing the Sagami River, a planned neighborhood of identical homes climbs the hillside for just a moment. Not a landmark — but the kind of view that makes those in the know glance up from their phone." },
    minutesFromTokyo: 27, side: "E", category: "notable", confidence: "verified", durationSec: 20, scene: "hills",
    image: "images/20260530_hinataoka.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-05-30",
      note: { ja: "カラフルな三角屋根が並ぶ「日向岡住宅」", en: "Colorful triangular roofs line up in Hinataoka." },
    },
    photos: [
      {
        src: "images/20260530_hinataoka_2_michikusa.jpg",
        alt: { ja: "新幹線のE席側から見える日向岡の住宅地", en: "Hinataoka hillside homes from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
        note: { ja: "カラフルな三角屋根が並ぶ「日向岡住宅」", en: "Colorful triangular roofs line up in Hinataoka." },
      },
    ],
    references: [REFERENCES.hinataokaRakumachi],
    map: { lat: 35.333, lng: 139.304, ja: "日向岡 住宅地 平塚", en: "Hinataoka Hiratsuka" },
  },
  {
    id: "ota-fuji",
    icon: "🗻",
    ja: { name: "都内からの富士山", area: "品川 → 新横浜（大田区付近）", hook: "東京を出て、最初の富士。", story: "品川を過ぎて新横浜へ向かう途中、空気が澄んだ日には大田区付近から富士山が見えることがあります。新富士の大きな富士山とは違う、都市の向こうに小さく浮かぶ早い合図。見えたら、その日の旅は少し幸先がいい。" },
    en: { name: "Mt. Fuji from Ota", area: "Shinagawa → Shin-Yokohama", hook: "The first Fuji after Tokyo.", story: "After Shinagawa, on the way toward Shin-Yokohama, Mt. Fuji can appear from around Ota on especially clear days. This is not the big Fuji near Shin-Fuji; it is a small early sign beyond the city. If you catch it, the journey starts with a quiet reward." },
    minutesFromTokyo: 10, side: "E", category: "notable", confidence: "needs-check", durationSec: 45, scene: "fuji",
    image: "images/20260509_ota_fuji_t_yangyang.jpg",
    photoCredit: {
      ja: "@T_Yangyang",
      en: "@T_Yangyang",
      url: "https://x.com/T_Yangyang/status/2056673343630426163",
      note: { ja: "大田区付近から見える富士山", en: "Mt. Fuji seen from around Ota." },
    },
    references: [REFERENCES.weatherFuji],
    map: { lat: 35.360625, lng: 138.727363, ja: "富士山（大田区付近からの遠望対象）", en: "Mt. Fuji, viewed from around Ota" },
  },
  {
    id: "maruko-bridge",
    icon: "🌉",
    ja: { name: "丸子橋", area: "品川 → 新横浜（多摩川付近）", hook: "多摩川に、青い橋。", story: "品川を過ぎて新横浜へ向かう途中、多摩川を渡る前後でE席側に丸子橋が見えます。東京のビル街から川の景色へ抜ける、旅の序盤の小さな切り替わり。映画「シン・ゴジラ」にも登場した橋で、背後には亀甲山古墳のある緑も重なります。車窓では一瞬ですが、青いアーチの形を覚えておくと見つけやすい橋です。" },
    en: { name: "Maruko Bridge", area: "Shinagawa → Shin-Yokohama, near the Tama River", hook: "A blue bridge over the Tama.", story: "After Shinagawa, as the train heads toward Shin-Yokohama, Maruko Bridge appears on the Seat E side around the Tama River. It is a small early shift from Tokyo's city blocks to river scenery. The bridge is also known from Shin Godzilla, and the green area behind it includes Kamenokoyama Kofun. The view is brief, but the blue arch shape makes it easier to spot." },
    minutesFromTokyo: 13, side: "E", category: "notable", confidence: "verified", durationSec: 18, scene: "bay",
    image: "images/20260704_maruko_bridge_1_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-07-04",
      note: { ja: "のぞみ27号・E席側、東京11:12発、11:25撮影", en: "Nozomi 27, Seat E side, Tokyo 11:12 departure, photographed at 11:25." },
    },
    photos: [
      {
        src: "images/20260704_maruko_bridge_2_michikusa.jpg",
        alt: { ja: "多摩川越しに見える丸子橋", en: "Maruko Bridge seen across the Tama River" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-07-04",
        note: { ja: "多摩川と河川敷越しに見える丸子橋", en: "Maruko Bridge beyond the Tama River and riverside fields" },
      },
      {
        src: "images/20250531_maruko_bridge_letus10.jpg",
        alt: { ja: "新幹線のE席側から見える丸子橋", en: "Maruko Bridge from Seat E" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/515810649.html",
        date: "2025-05-31",
        note: { ja: "橋の形がわかりやすい車窓写真", en: "A window photo that clearly shows the bridge shape" },
      },
      {
        src: "images/20260629_2320_maruko_bridge_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見える丸子橋付近", en: "Around Maruko Bridge at night from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-06-29",
        note: { ja: "夜の多摩川に続く橋の灯り", en: "Bridge lights stretching across the night Tama River" },
      },
    ],
    references: [REFERENCES.marukoBridgeBlog],
    map: { lat: 35.58537, lng: 139.66883, ja: "丸子橋 多摩川", en: "Maruko Bridge Tama River" },
  },
  {
    id: "musashi-kosugi-towers",
    icon: "🏙️",
    ja: { name: "武蔵小杉のタワマン群", area: "品川 → 新横浜（武蔵小杉付近）", hook: "川を越えた、塔の街。", story: "東京から新大阪へ向かうと、丸子橋を過ぎてすぐ、E席側に武蔵小杉のタワマン群が迫ります。多摩川の開けた景色から、縦に伸びる街へ一気に切り替わる瞬間。名所というより、首都圏の密度をそのまま見せる車窓です。昼は建物の高さが、夜は窓明かりの層が印象に残ります。" },
    en: { name: "Musashi-Kosugi Towers", area: "Shinagawa → Shin-Yokohama, around Musashi-Kosugi", hook: "A wall of towers after the river.", story: "Heading from Tokyo toward Shin-Osaka, just after Maruko Bridge, the Musashi-Kosugi high-rise towers appear on the Seat E side. The view shifts suddenly from the open Tama River to a dense vertical city. It is not a classic landmark, but it captures the scale of Greater Tokyo from the train window. By day the height stands out; at night, the stacked window lights do." },
    minutesFromTokyo: 14, side: "E", category: "notable", confidence: "verified", durationSec: 35, scene: "hills",
    image: "images/20260704_musashi_kosugi_towers_1_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-07-04",
      note: { ja: "のぞみ27号・E席側、東京11:12発、11:26撮影", en: "Nozomi 27, Seat E side, Tokyo 11:12 departure, photographed at 11:26." },
    },
    photos: [
      {
        src: "images/20260704_musashi_kosugi_towers_2_michikusa.jpg",
        alt: { ja: "新幹線のE席側から見える武蔵小杉のタワマン群", en: "Musashi-Kosugi towers from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-07-04",
        note: { ja: "丸子橋を過ぎてすぐに見えるタワマン群", en: "High-rise residential towers just after Maruko Bridge" },
      },
      {
        src: "images/20260629_musashi_kosugi_towers_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見える武蔵小杉のタワマン群", en: "Musashi-Kosugi towers at night from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-06-29",
        note: { ja: "夜は窓明かりが積み重なる街並みに変わる", en: "At night, stacked apartment lights change the view" },
      },
    ],
    map: { lat: 35.57563, lng: 139.661659, ja: "武蔵小杉駅周辺のタワーマンション群", en: "Musashi-Kosugi high-rise cluster" },
  },
  {
    id: "putiputi-sign",
    icon: "🫧",
    ja: { name: "プチプチ看板", area: "新横浜 → 小田原（藤沢市付近）", hook: "謎のプチプチ看板。", story: "新横浜から小田原へ向かう途中、A席側にプチプチ®系の看板が見えます。沿線の看板は時々変わりますが、2026年7月時点では「私は誰でしょう」と問いかける謎の看板になっていました。隣にはおなじみの727 COSMETICS看板。名所ではない。でも見つけた瞬間、移動中の景色が少しだけ自分のものになる。短い出会いなので、少し幅を持って探してください。" },
    en: { name: "PUTIPUTI Sign", area: "Shin-Yokohama → Odawara, around Fujisawa", hook: "A mystery PUTIPUTI sign.", story: "Between Shin-Yokohama and Odawara, a PUTIPUTI-like sign appears on the Seat A side. The trackside sign changes from time to time; as of July 2026, it had become a small mystery asking, 'Who am I?' Beside it is the familiar 727 COSMETICS sign. It is not a major landmark, but it is exactly the kind of small discovery that makes the ride feel personal. It is quick, so start watching with a little margin." },
    minutesFromTokyo: 29, side: "A", category: "curious", confidence: "verified", durationSec: 12, scene: "hills",
    image: "images/20260704_putiputi_sign_2_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-07-04",
      note: { ja: "のぞみ27号・A席側、東京11:12発、11:41撮影。2026年7月時点の謎看板", en: "Nozomi 27, Seat A side, Tokyo 11:12 departure, photographed at 11:41. The July 2026 mystery sign." },
    },
    photos: [
      {
        src: "images/20260704_putiputi_sign_1_michikusa.jpg",
        alt: { ja: "プチプチ系看板と727看板", en: "PUTIPUTI-like sign and a 727 sign" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-07-04",
        note: { ja: "A席側。となりにはおなじみの727 COSMETICS看板", en: "Seat A side. The familiar 727 COSMETICS sign sits next to it." },
      },
      {
        src: "images/20190127_putiputi_sign_putiputi0808.jpg",
        alt: { ja: "以前のプチプチ看板", en: "Earlier PUTIPUTI sign" },
        credit: { ja: "プチプチ®の川上産業 @PUTIPUTI_0808", en: "Kawakami Sangyo PUTIPUTI® @PUTIPUTI_0808" },
        sourceUrl: "https://x.com/PUTIPUTI_0808/status/1089401678594433025",
        note: { ja: "川上産業（株）の公式アカウントより。以前の看板", en: "From Kawakami Sangyo's official account. Earlier sign." },
      },
    ],
    references: [
      {
        label: { ja: "OCEANS: プチプチの話", en: "OCEANS: Story of PUTIPUTI (Japanese only)" },
        url: {
          ja: "https://oceans.tokyo.jp/article/detail/30210",
          en: "https://www.putiputi.co.jp/en/products-en/3005",
        },
      },
    ],
    map: { lat: 35.321496, lng: 139.285829, ja: "プチプチ看板付近（727 No.22近接候補）", en: "PUTIPUTI sign area near 727 No.22" },
  },
  {
    id: "727-board",
    icon: "7️⃣",
    ja: { name: "727看板", area: "新横浜 → 小田原（藤沢市付近）", hook: "田んぼの中に、727。", story: "新横浜を出て少しすると、藤沢市葛原付近のE席側に、727 COSMETICSの白い看板が見えます。新幹線からは一瞬で通り過ぎるため「何の広告だろう」と気になりやすい、沿線広告の代表格です。この葛原付近の看板はE席側ですが、さらに進んだ用田付近やプチプチ看板の隣に見えるものはA席側。727は沿線に複数あり、席側も地点で変わります。隣の黄色い「248」は、最近は高速道路だけでなく新幹線の車窓でもよく見かける、きぬた歯科系の看板です。" },
    en: { name: "727 Cosmetics Signs", area: "Shin-Yokohama → Odawara, around Fujisawa", hook: "727 in the fields.", story: "A little after Shin-Yokohama, a white 727 COSMETICS sign appears on the Seat E side around Kuzuhara in Fujisawa. The Kuzuhara sign is on Seat E, while other nearby 727 signs, including the ones around Yoda and beside the PUTIPUTI sign, are on Seat A. The signs are scattered along Shinkansen lines, so the side changes by location. Because each one flashes by in seconds, many riders start wondering what the mysterious '727' signs are." },
    minutesFromTokyo: 26, side: "E", sideLabel: { ja: "A席・E席", en: "Seats A and E" }, category: "curious", confidence: "verified", durationSec: 30, scene: "hills",
    image: "images/20260704_727_board_kuzuhara_2_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-07-04",
      note: { ja: "のぞみ27号・E席側、東京11:12発、11:38撮影。藤沢市葛原付近", en: "Nozomi 27, Seat E side, Tokyo 11:12 departure, photographed at 11:38 near Kuzuhara, Fujisawa." },
    },
    photos: [
      {
        src: "images/20260704_727_board_kuzuhara_1_michikusa.jpg",
        alt: { ja: "248看板と並ぶ727 COSMETICS看板", en: "727 COSMETICS sign beside the 248 sign" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-07-04",
        note: { ja: "E席側。248看板と、みんなの介護看板の間に見える727", en: "Seat E side. 727 between the 248 sign and a care-service sign." },
      },
      {
        src: "images/20260629_727_board_2_2x_michikusa.jpg",
        alt: { ja: "新幹線のA席側から見える727 COSMETICS看板", en: "727 COSMETICS sign from Seat A" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-06-29",
        note: { ja: "のぞみ99号・A席側、6:18撮影。用田付近のうち東京寄りの727看板。黄色い歯科看板の隣", en: "Nozomi 99, Seat A side, photographed at 6:18. The Tokyo-side 727 sign near Yoda, beside a yellow dental sign." },
      },
      {
        src: "images/20260629_727_board_1_4x_michikusa.jpg",
        alt: { ja: "新幹線のA席側から見える727 COSMETICS看板", en: "727 COSMETICS sign from Seat A" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-06-29",
        note: { ja: "のぞみ99号・A席側、6:18撮影。藤沢市用田付近", en: "Nozomi 99, Seat A side, photographed at 6:18 near Yoda, Fujisawa." },
      },
    ],
    references: [REFERENCES.sevenTwoSevenNote, REFERENCES.sevenTwoSevenOfficial],
    map: { lat: 35.4167, lng: 139.428027, ja: "727看板 藤沢市葛原", en: "727 sign, Kuzuhara Fujisawa" },
  },
  {
    id: "sagami-fuji",
    icon: "🗻",
    ja: { name: "相模平野の富士山", area: "新横浜 → 小田原", hook: "平野の向こうに富士。", story: "新横浜から小田原へ向かう途中、相模川が作った平野の向こうに、富士山が見える区間があります。丹沢山地と箱根山系のあいだから顔を出す、東京を出て最初に探したい富士山。新富士付近の主役とは違う、遠望の楽しさがあります。" },
    en: { name: "Mt. Fuji over Sagami Plain", area: "Shin-Yokohama → Odawara", hook: "Fuji beyond the plain.", story: "Between Shin-Yokohama and Odawara, Mt. Fuji can appear beyond the alluvial plain made by the Sagami River, framed by the Tanzawa and Hakone mountains. It is the first Fuji worth looking for after leaving Tokyo: not the big main event near Shin-Fuji, but a distant view with its own thrill." },
    minutesFromTokyo: 27, side: "E", category: "notable", confidence: "verified", durationSec: 120, scene: "fuji",
    image: "images/20260530_sagami_fuji_hiratsuka_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-05-30",
      note: { ja: "平塚市内から、相模平野越しに見える富士山", en: "Mt. Fuji beyond Sagami Plain from Hiratsuka." },
    },
    photos: [
      {
        src: "images/20260530_sagami_fuji_samukawa_michikusa.jpg",
        alt: { ja: "寒川町付近から見える相模平野越しの富士山", en: "Mt. Fuji beyond Sagami Plain near Samukawa" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
        note: { ja: "丹沢・箱根の山なみの奥に富士山", en: "Mt. Fuji behind the Tanzawa and Hakone mountains" },
      },
      {
        src: "images/20240114_sagami_fuji_odawara_michikusa.jpg",
        alt: { ja: "小田原付近から見える富士山", en: "Mt. Fuji seen near Odawara" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2024-01-14",
        note: { ja: "小田原に近づくころの富士山", en: "Mt. Fuji as Odawara approaches" },
      },
    ],
    references: [REFERENCES.weatherFuji],
    map: { lat: 35.360625, lng: 138.727363, ja: "富士山（相模平野からの遠望対象）", en: "Mt. Fuji, viewed across Sagami Plain" },
  },
  {
    id: "odawara",
    icon: "🌊",
    ja: { name: "熱海と相模湾", area: "小田原 → 熱海", hook: "街の景色が、海の旅に切りかわる合図。", story: "小田原を過ぎ、熱海が近づくころ、車窓は相模湾へ大きくひらきます。山肌の街、海、岬が一枚の絵になって、東京の街なみが「旅の景色」に変わる瞬間です。海側のA席をどうぞ。" },
    en: { name: "Atami & Sagami Bay", area: "Odawara → Atami", hook: "Where the sea begins.", story: "After Odawara, as Atami approaches, the window opens wide toward Sagami Bay. Hillside town, sea and headlands fold into one view: the moment the ride stops being a commute and starts being a journey. Look from Seat A." },
    minutesFromTokyo: 36, side: "A", category: "classic", confidence: "verified", durationSec: 120, scene: "bay",
    image: "images/20260515_atami_sagami_bay.jpg",
    photoCredit: { ja: "michikusa", en: "michikusa", date: "2026-05-15" },
    photos: [
      {
        src: "images/20250523_hatsushima_letus10.jpg",
        alt: { ja: "新幹線のA席側から見える初島", en: "Hatsushima Island from Seat A" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/516720935.html",
        note: { ja: "初島: 静岡県唯一の有人島", en: "Hatsushima: Shizuoka's only inhabited island" },
      },
      {
        src: "images/20250524_atami_castle_letus10.jpg",
        alt: { ja: "新幹線のA席側から見える熱海城", en: "Atami Castle from Seat A" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/516721203.html",
        note: { ja: "熱海城: 1959年竣工の観光施設", en: "Atami Castle: a sightseeing facility completed in 1959" },
      },
    ],
    references: [REFERENCES.atami, REFERENCES.hatsushimaBlog, REFERENCES.atamiCastleBlog],
    map: { lat: 35.0864250, lng: 139.0786972, ja: "熱海城", en: "Atami Castle" },
  },
  {
    id: "odawara-castle",
    icon: "🏯",
    ja: { name: "小田原城", area: "小田原駅付近", hook: "のぞみでは、まばたきする間の城。", story: "小田原駅の前後、A席側に小田原城が一瞬だけ見えます。停車しない列車では本当に短い出会い。見えたら、それだけで旅の序章に小さな印がつきます。" },
    en: { name: "Odawara Castle", area: "Around Odawara Sta.", hook: "A castle in a blink.", story: "Around Odawara Station, Odawara Castle flashes by on the Seat A side. On Nozomi services that pass through without stopping, the moment is astonishingly short: a small mark at the beginning of the journey." },
    minutesFromTokyo: 31, side: "A", category: "notable", confidence: "verified", durationSec: 8, scene: "castle",
    image: "images/20251112_odawara_castle_castle_traveler.jpg",
    photoCredit: {
      ja: "@Castle_Traveler",
      en: "@Castle_Traveler",
      url: "https://x.com/Castle_Traveler/status/1992009734854218106",
      note: { ja: "のぞみではほんとに一瞬", en: "On Nozomi, it really is over in a blink." },
    },
    photos: [
      {
        src: "images/20250526_odawara_castle_letus10.jpg",
        alt: { ja: "新幹線のA席側から見える小田原城", en: "Odawara Castle from Seat A" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/516754194.html",
        note: { ja: "のぞみではほんとに一瞬", en: "On Nozomi, it really is over in a blink." },
      },
    ],
    references: [REFERENCES.odawaraCastle, REFERENCES.odawaraCastleBlog],
    map: { lat: 35.2509722, lng: 139.1535778, ja: "小田原城", en: "Odawara Castle" },
  },
  {
    id: "gyoran-kannon",
    icon: "🙏",
    ja: { name: "魚籃観音像", area: "小田原 → 熱海（早川付近）", hook: "一瞬だけ、白い観音様。", story: "小田原を過ぎ、早川駅の近くでA席側を見ていると、白い観音像がほんの一瞬あらわれます。車窓に突然立つ姿は、見逃すと「あれは何だったんだろう」となる発見型スポット。魚籃観音は魚や海にゆかりのある観音様で、小田原らしい海辺の道草です。" },
    en: { name: "Gyoran Kannon Statue", area: "Odawara → Atami, near Hayakawa", hook: "A white Kannon, for a heartbeat.", story: "Just after Odawara, near Hayakawa Station, a white Kannon statue appears for only a moment on the Seat A side. It is the kind of sudden window-seat sight that leaves you wondering what you just saw. Gyoran Kannon is associated with fish and the sea, making this a quietly Odawara-like discovery." },
    minutesFromTokyo: 33, side: "A", category: "curious", confidence: "verified", durationSec: 2, scene: "pagoda",
    image: "images/20260516_gyoran_kannon_michikusa.jpg",
    photoCredit: { ja: "michikusa", en: "michikusa", date: "2026-05-16" },
    references: [REFERENCES.gyoranKannon],
    map: { lat: 35.2426, lng: 139.1384, ja: "東善院 魚籃観音 小田原 早川", en: "Tozen-in Gyoran Kannon Odawara Hayakawa" },
  },
  {
    id: "fuji",
    icon: "🗻",
    ja: { name: "富士山", area: "三島 → 新富士", hook: "日本でいちばん有名な3分間。", story: "三島から新富士のあいだ、富士山が車窓いっぱいに迫ります。見えている時間はおよそ3〜4分。トンネルを抜けるたびに大きくなる富士山は、何度乗っても声が出ます。E席側、少し前から窓の外を。" },
    en: { name: "Mt. Fuji", area: "Mishima → Shin-Fuji", hook: "Japan's famous three minutes.", story: "Between Mishima and Shin-Fuji, Mt. Fuji fills the window — for roughly three to four minutes. It grows bigger after each tunnel, and it gets a gasp out of people every single time. Seat E side; be ready a little early." },
    minutesFromTokyo: 43, side: "E", category: "classic", confidence: "verified", durationSec: 210, scene: "fuji",
    image: "images/20210218_fuji_rumireport.jpg",
    photoCredit: {
      ja: "@rumireport",
      en: "@rumireport",
      url: "https://x.com/rumireports/status/1362350607273586688",
      note: { ja: "夕暮れ時は富士山が最も美しい瞬間の一つ", en: "Dusk is one of Mt. Fuji's most beautiful moments." },
    },
    photos: [
      {
        src: "images/20240211_fuji_michikusa.jpg",
        alt: { ja: "新幹線のE席側から見える富士山", en: "Mt. Fuji from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2024-02-11",
        note: { ja: "雪化粧の富士山はいつ見ても美しい", en: "Snow-capped Mt. Fuji is beautiful every time." },
      },
      {
        src: "images/20260616_fuji_sttraveler.jpg",
        alt: { ja: "新幹線のE席側から見える富士山", en: "Mt. Fuji from Seat E" },
        credit: { ja: "@STTraveler", en: "@STTraveler" },
        sourceUrl: "https://x.com/STTraveler/status/2066661705372033042",
        note: { ja: "田んぼの緑とのコントラストが美しい", en: "The contrast with the green rice fields is beautiful." },
      },
      {
        src: "images/20260619_fuji_sttraveler.jpg",
        alt: { ja: "新幹線のE席側から見える富士山", en: "Mt. Fuji from Seat E" },
        credit: { ja: "@STTraveler", en: "@STTraveler" },
        sourceUrl: "https://x.com/STTraveler/status/2067980954287951976",
        note: { ja: "街並みの向こうにうっすらと浮かぶ幻想的な富士山", en: "A dreamlike Mt. Fuji faintly floating beyond the town." },
      },
      {
        src: "images/20230913_fuji_michikusa.jpg",
        alt: { ja: "新幹線のE席側から見える富士山", en: "Mt. Fuji from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2023-09-13",
        note: { ja: "小麦色の田んぼと雪のない富士山の対比もまた美しい", en: "The contrast between wheat-colored fields and a snowless Fuji is beautiful too." },
      },
      {
        src: "images/20260516_fuji_michikusa.jpg",
        alt: { ja: "新幹線のE席側から見える富士山", en: "Mt. Fuji from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-16",
      },
    ],
    references: [REFERENCES.weatherFuji],
    map: { lat: 35.360625, lng: 138.727363, ja: "富士山", en: "Mt. Fuji" },
  },
  {
    id: "left-fuji",
    icon: "🔭",
    ja: { name: "左富士", area: "新富士 → 静岡", hook: "海側A席に、28秒だけ富士山。", story: "ふつう富士山はE席のもの。でも線路がカーブするこの区間だけ、反対のA席側に富士山があらわれます。昔から「幸運の左富士」とも呼ばれる、短いごほうびのような車窓。見えるのはほんの数十秒。A席のあなたにも、ちゃんと出番があります。" },
    en: { name: "Left-Side Fuji", area: "Shin-Fuji → Shizuoka", hook: "For 28 seconds, Fuji switches sides.", story: "Mt. Fuji normally belongs to Seat E. But where the track curves in this section, Fuji appears briefly on the opposite A side. Known as a lucky left-side Fuji, it is a tiny window-seat reward that lasts only a few seconds. Seat A gets its moment too." },
    minutesFromTokyo: 54, side: "A", category: "notable", confidence: "verified", durationSec: 28, scene: "leftfuji",
    image: "images/20240410_left_fuji_earlyretiremile.jpg",
    photoCredit: { ja: "@earlyretiremile", en: "@earlyretiremile", url: "https://x.com/earlyretiremile/status/1777853629682405657" },
    photos: [
      {
        src: "images/20260513_left_fuji.jpg",
        alt: { ja: "新幹線のA席側から見える左富士", en: "Left-side Fuji from Seat A" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-13",
        note: { ja: "雪がないと見つけるのがさらに大変。", en: "Without snow, it is even harder to spot." },
      },
      {
        src: "images/20241212_left_fuji_kawasan3.jpg",
        alt: { ja: "新幹線のA席側から見える冬の左富士", en: "Winter Left-Side Fuji from Seat A" },
        credit: { ja: "@kawasan3", en: "@kawasan3" },
        sourceUrl: "https://x.com/kawasan3/status/1866984276581028088",
      },
    ],
    references: [REFERENCES.leftFujiTrafficNews],
    map: { lat: 35.360625, lng: 138.727363, ja: "富士山", en: "Mt. Fuji" },
  },
  {
    id: "shimizu-port-chikyu",
    icon: "🏗️",
    ja: { name: "清水港とちきゅう", area: "新富士 → 静岡", hook: "港のクレーンと、ちきゅう。", story: "新富士から静岡へ向かう途中、A席側に清水港のクレーン群が見えてきます。停泊していれば、地球深部探査船「ちきゅう」も窓に入ります。富士山のあとに、今度は港の巨大構造物が現れる。山と海と工業の距離が近い、静岡らしい車窓です。" },
    en: { name: "Shimizu Port and CHIKYU", area: "Shin-Fuji → Shizuoka", hook: "Cranes and CHIKYU.", story: "Between Shin-Fuji and Shizuoka, look from Seat A for Shimizu Port: gantry cranes, and sometimes the deep-sea drilling vessel CHIKYU. After Mt. Fuji, another kind of scale appears outside the window: mountains, sea, and industry all close together." },
    minutesFromTokyo: 50, side: "A", category: "notable", confidence: "source-backed", durationSec: 70, scene: "bay",
    image: "images/20240119_shimizu_port_chikyu_senba16530315.jpg",
    photoCredit: {
      ja: "@senba16530315",
      en: "@senba16530315",
      url: "https://x.com/senba16530315/status/1748226462862508427",
      note: { ja: "ガントリークレーンの合間に見える、停泊中の「ちきゅう」の巨大なデリック", en: "CHIKYU's huge derrick, docked between the gantry cranes" },
    },
    photos: [
      {
        src: "images/20260629_shimizu_port_chikyu_morning_michikusa.jpg",
        alt: { ja: "朝の新幹線から見える清水港とちきゅう", en: "Shimizu Port and CHIKYU in the morning from the Shinkansen" },
        date: "2026-06-29",
        note: { ja: "朝の港に、ちきゅう", en: "CHIKYU in the morning port" },
      },
      {
        src: "images/20260629_2242_shimizu_port_chikyu_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見える清水港とちきゅう", en: "Shimizu Port and CHIKYU at night from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-06-29",
        note: { ja: "夜の港に、ちきゅう", en: "CHIKYU in the night port" },
      },
    ],
    references: [REFERENCES.shimizuPort],
    map: { lat: 35.0092, lng: 138.4961, ja: "清水港 地球深部探査船ちきゅう", en: "Shimizu Port CHIKYU" },
  },
  {
    id: "shizuoka-tea-fields",
    icon: "🍵",
    ja: { name: "静岡の茶畑", area: "静岡 → 掛川", hook: "緑の畝が、車窓を走る。", story: "掛川城の少し手前、車窓に茶畑の緑が流れる区間があります。富士山や城ほど大きな目印ではありません。でも、東海道新幹線で静岡を走っていることが一瞬でわかる、日本らしい車窓です。掛川が近づいたら、窓の外の畑の模様に注目してみてください。" },
    en: { name: "Shizuoka Tea Fields", area: "Shizuoka → Kakegawa", hook: "Rows of green tea from the window.", story: "A little before Kakegawa Castle, rows of tea fields can slide past the window. It is not as obvious as Mt. Fuji or a castle, but it tells you immediately that you are crossing Shizuoka. As Kakegawa approaches, watch for the patterned green fields outside." },
    minutesFromTokyo: 61, side: "E", category: "notable", confidence: "verified", durationSec: 50, scene: "hills",
    image: "images/20260530_shizuoka_tea_fields_1_michikusa.jpg",
    photoCredit: { ja: "michikusa", en: "michikusa", date: "2026-05-30" },
    photos: [
      {
        src: "images/20260530_shizuoka_tea_fields_2_michikusa.jpg",
        alt: { ja: "新幹線から見える静岡の茶畑", en: "Shizuoka tea fields from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
      },
    ],
    references: [REFERENCES.shizuokaTeaTourism],
    map: { lat: 34.814591, lng: 138.127321, ja: "静岡の茶畑（代表通過地点）", en: "Shizuoka tea fields representative viewpoint" },
  },
  {
    id: "kakegawa",
    icon: "🏯",
    ja: { name: "掛川城", area: "掛川駅 前後", hook: "駅のすぐそばに、木造復元の天守。", story: "掛川駅の北側、車窓から探せる距離に掛川城の天守があります。日本初の木造復元天守。見えるのは一瞬ですが、静岡の車窓に歴史の一行が足されます。" },
    en: { name: "Kakegawa Castle", area: "Around Kakegawa Sta.", hook: "A castle keep, right by the tracks.", story: "Just north of Kakegawa Station stands Kakegawa Castle — Japan's first wooden-reconstructed keep. It appears only briefly, but it adds a line of history to the Shizuoka stretch." },
    minutesFromTokyo: 62, side: "E", category: "notable", confidence: "verified", durationSec: 15, scene: "castle",
    image: "images/20220312_kakegawa_castle_neoromancefan.jpg",
    photoCredit: { ja: "@NeoRomanceFan", en: "@NeoRomanceFan", url: "https://x.com/NeoRomanceFan/status/1502633820075352064" },
    photos: [
      {
        src: "images/20260530_kakegawa_castle.jpg",
        alt: { ja: "新幹線のE席側から見える掛川城", en: "Kakegawa Castle from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
      },
    ],
    references: [REFERENCES.kakegawaCastle],
    map: { lat: 34.775417, lng: 138.0147333, ja: "掛川城", en: "Kakegawa Castle" },
  },
  {
    id: "genki-sign",
    icon: "💬",
    ja: { name: "元気が出る看板", area: "掛川 → 浜松（磐田付近）", hook: "しっぺいの応援看板。", story: "掛川を過ぎて浜松へ向かう途中、ハウス食品静岡工場を過ぎて少ししたあたりのE席側に、短い応援メッセージの野立て看板が並びます。「いつも 応援してるよ」「みんな ありがとう」「必ず 明日があるからね」。ポジティブなメッセージを車窓で見つけると、少し元気が出ます。遠く小さく見えるので、文字を読み切るより、磐田市のキャラクター・しっぺいがいる三連続看板として探すのがコツです。" },
    en: { name: "Cheer-up Signs", area: "Kakegawa → Hamamatsu, near Iwata", hook: "Shippei's cheer-up signs.", story: "After Kakegawa, heading toward Hamamatsu, a row of small roadside signs appears on the Seat E side shortly after the House Foods Shizuoka Factory area. The messages are simple and encouraging: 'I'm always rooting for you,' 'Thank you, everyone,' and 'There will always be tomorrow.' Catching a positive message from the train can give the ride a small lift. From the Shinkansen they are distant and quick, so look for the three signs with Shippei, Iwata City's white dog character, rather than trying to read every word." },
    minutesFromTokyo: 64, side: "E", category: "curious", confidence: "verified", durationSec: 18, scene: "hills",
    image: "images/20250608_genki_sign_letus10.jpg",
    photoCredit: {
      ja: "@letus10 / 新幹線の車窓から",
      en: "@letus10 / Shinkansen window blog",
      url: "https://cotetu.seesaa.net/article/516019488.html",
      note: { ja: "掛川・浜松間、山側・E席から見える三連続の応援看板", en: "Three cheer-up signs between Kakegawa and Hamamatsu, seen from Seat E." },
    },
    photos: [
      {
        src: "images/20260704_genki_sign_michikusa.jpg",
        alt: { ja: "新幹線のE席側から遠くに見える元気が出る看板", en: "Cheer-up signs seen in the distance from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-07-04",
        note: { ja: "のぞみ27号・E席側、東京11:12発、12:18撮影", en: "Nozomi 27, Seat E side, Tokyo 11:12 departure, photographed at 12:18." },
      },
    ],
    references: [REFERENCES.genkiSignBlog, REFERENCES.genkiSignStreetView],
    map: { lat: 34.7298265, lng: 137.8986674, ja: "磐田 元気が出る看板", en: "Iwata cheer-up signs" },
  },
  {
    id: "hamanako",
    icon: "🚤",
    ja: { name: "浜名湖", area: "浜松 → 豊橋", hook: "列車が、湖の上をはしる。", story: "浜松を出てしばらくすると、車窓の両側に浜名湖の水面がひろがります。E席側だけでなく、A席側にも水辺や橋が見える区間です。晴れて空気が澄んでいれば、湖の向こうに富士山が見えることもあります。光る湖面とうなぎの養殖いかだを楽しみつつ、遠くの富士山も少し探してみてください。" },
    en: { name: "Lake Hamana", area: "Hamamatsu → Toyohashi", hook: "The train runs over the water.", story: "After Hamamatsu, Lake Hamana spreads out on both sides of the train. It is not only a Seat E view; Seat A also gets water, bridges, and open sky. On clear days with crisp air, Mt. Fuji can sometimes appear beyond the lake. Enjoy the bright water and eel-farming rafts, and keep a small lookout for distant Fuji too." },
    minutesFromTokyo: 73, side: "E", sideLabel: { ja: "A席・E席", en: "Seats A and E" }, category: "classic", confidence: "verified", durationSec: 150, scene: "lake",
    image: "images/20260505_hamanako_design_photosy.jpg",
    photoCredit: {
      ja: "@Design_photoSY",
      en: "@Design_photoSY",
      url: "https://x.com/Design_photoSY/status/2051484905377521740",
      note: { ja: "E席から見る浜名湖。まるで海の上を走っているかのよう", en: "Lake Hamana from Seat E, as if the train were running over the sea" },
    },
    photos: [
      {
        src: "images/20260505_hamanako_design_photosy_2.jpg",
        alt: { ja: "新幹線のE席側から見える浜名湖", en: "Lake Hamana from Seat E" },
        credit: { ja: "@Design_photoSY", en: "@Design_photoSY" },
        sourceUrl: "https://x.com/Design_photoSY/status/2051484905377521740",
        note: { ja: "E席（山側）から見える湖面", en: "Lake view from Seat E, mountain side" },
      },
      {
        src: "images/20260530_hamanako.jpg",
        alt: { ja: "新幹線のE席側から見える浜名湖", en: "Lake Hamana from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
        note: { ja: "E席（山側）から見える浜名湖", en: "Lake Hamana from Seat E, mountain side" },
      },
      {
        src: "images/20260516_hamanako_seaside_1_michikusa.jpg",
        alt: { ja: "新幹線のA席側から見える浜名湖", en: "Lake Hamana from Seat A" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-16",
        note: { ja: "A席（海側）から見える浜名湖", en: "Lake Hamana from Seat A, sea side" },
      },
      {
        src: "images/20260516_hamanako_seaside_2_michikusa.jpg",
        alt: { ja: "新幹線のA席側から見える浜名湖", en: "Lake Hamana from Seat A" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-16",
        note: { ja: "A席（海側）から見える水辺", en: "Waterside view from Seat A, sea side" },
      },
      {
        src: "images/20250612_hamanako_torii_letus10.jpg",
        alt: { ja: "新幹線から一瞬見える弁天島の赤鳥居", en: "Bentenjima red torii briefly visible from the Shinkansen" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/517074141.html",
        note: { ja: "A席（海側）から、ビルの谷間に一瞬だけ見える赤鳥居", en: "From Seat A, sea side: a red torii appears briefly between buildings" },
      },
      {
        src: "images/20260516_hamanako_torii_michikusa.jpg",
        alt: { ja: "新幹線のA席側から見える弁天島の赤鳥居", en: "Bentenjima red torii from Seat A" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-16",
        note: { ja: "A席（海側）から、ビルの谷間に一瞬だけ見える赤鳥居", en: "From Seat A, sea side: a red torii appears briefly between buildings" },
      },
    ],
    relatedSpotIds: ["hamanako-fuji"],
    references: [REFERENCES.hamanakoTourism, REFERENCES.hamanakoToriiBlog],
    map: { lat: 34.741111, lng: 137.569722, ja: "浜名湖", en: "Lake Hamana" },
  },
  {
    id: "hamanako-fuji",
    icon: "🗻",
    ja: { name: "浜名湖越しの富士山", area: "浜松 → 豊橋", hook: "湖の向こうに、富士山。", story: "浜名湖を渡るころ、条件がそろうと遠くに富士山が見えることがあります。新富士付近の迫力とはまったく違う、湖と空の奥に小さく探す富士山。晴れた冬の日など、空気が澄んだときだけのレアな車窓です。" },
    en: { name: "Mt. Fuji beyond Lake Hamana", area: "Hamamatsu → Toyohashi", hook: "Fuji beyond the lake.", story: "Around Lake Hamana, Mt. Fuji can sometimes be seen far in the distance when the air is clear. It is nothing like the dramatic close view near Shin-Fuji: this is a tiny Fuji to search for beyond the lake and sky, a rare window-seat bonus on crisp clear days." },
    minutesFromTokyo: 73, side: "E", category: "notable", confidence: "source-backed", durationSec: 150, scene: "fuji",
    image: "images/250111_hamanako_fuji_proboffin.jpg",
    photoCredit: {
      ja: "@ProBoffin",
      en: "@ProBoffin",
      url: "https://x.com/ProBoffin/status/1877874599360389543",
      note: { ja: "浜名湖から見える富士山", en: "Mt. Fuji from Lake Hamana" },
    },
    photos: [
      {
        src: "images/20191203_hamanako_fuji_kawasan3.jpg",
        alt: { ja: "浜名湖から見える遠くの富士山", en: "Distant Mt. Fuji seen from Lake Hamana" },
        credit: { ja: "かわさん @kawasan3", en: "Kawasan @kawasan3" },
        sourceUrl: "https://x.com/kawasan3/status/2071620687626973333",
        note: { ja: "湖の向こうに小さく見える富士山", en: "A tiny Fuji beyond the lake" },
      },
      {
        src: "images/190103_hamanako_fuji_sentokia.jpg",
        alt: { ja: "浜名湖から見える富士山", en: "Mt. Fuji seen from Lake Hamana" },
        credit: { ja: "@sentokia", en: "@sentokia" },
        sourceUrl: "https://x.com/sentokia/status/1080626377701748737",
        note: { ja: "サンマリンブリッジの右奥に小さく富士山", en: "Mt. Fuji is small beyond the right side of Sun Marine Bridge" },
      },
    ],
    relatedSpotIds: ["hamanako"],
    references: [REFERENCES.hamanakoTourism, REFERENCES.weatherFuji],
    map: { lat: 34.741111, lng: 137.569722, ja: "浜名湖 富士山", en: "Lake Hamana Mt. Fuji" },
  },
  {
    id: "toyohashi-tateiwa",
    icon: "🪨",
    ja: { name: "豊橋の立岩", area: "浜松 → 豊橋", hook: "浜名湖のあと、岩が立つ。", story: "東京から大阪方面へ向かう新幹線で、浜名湖を過ぎて少しすると、丘の上に岩が突き出した景色が見えてきます。豊橋の立岩。偶然見つけて、気になった人も多いかもしれません。浜名湖の余韻が残るうちに、山側の窓を見てみてください。" },
    en: { name: "Toyohashi Tateiwa Rock", area: "Hamamatsu → Toyohashi", hook: "A standing rock after Lake Hamana.", story: "On a Shinkansen heading from Tokyo toward Osaka, shortly after Lake Hamana, a rock jutting up from a hill comes into view on the mountain side. This is Toyohashi Tateiwa. Many riders may have noticed it by chance and wondered what it was. While Lake Hamana is still fresh in memory, keep an eye on the Seat E window." },
    minutesFromTokyo: 75, side: "E", category: "curious", confidence: "verified", durationSec: 20, scene: "mountain",
    image: "images/20210923_toyohashi_tateiwa_pato727.jpg",
    photoCredit: {
      ja: "@Pato_727",
      en: "@Pato_727",
      url: "https://x.com/Pato_727/status/1443264581577502720",
      note: { ja: "2021年9月23日新幹線の車窓から撮影", en: "Shot from the Shinkansen window on September 23, 2021" },
    },
    photos: [
      {
        src: "images/20191027_toyohashi_tateiwa_aosemi1995.jpg",
        alt: { ja: "新幹線のE席側から見える豊橋の立岩", en: "Toyohashi Tateiwa Rock from Seat E" },
        credit: { ja: "@aosemi1995", en: "@aosemi1995" },
        sourceUrl: "https://x.com/aosemi1995/status/1188265245686427654",
        note: { ja: "新幹線の窓から一瞬見える不思議な岩山", en: "A mysterious rocky hill that appears briefly from the Shinkansen window" },
      },
      {
        src: "images/20220626_toyohashi_tateiwa_suyqs3wr42jnm5i.jpg",
        alt: { ja: "車窓から見える豊橋の立岩", en: "Toyohashi Tateiwa Rock from the train window" },
        credit: { ja: "@SUyqs3wR42jNm5I", en: "@SUyqs3wR42jNm5I" },
        sourceUrl: "https://x.com/SUyqs3wR42jNm5I/status/1541009819804778497",
        note: { ja: "実際に見るとその雄大さに感動", en: "Its scale is moving when seen in person" },
      },
    ],
    references: [REFERENCES.toyohashiTateiwa],
    map: { lat: 34.7258063, lng: 137.4706861, ja: "豊橋 立岩", en: "Toyohashi Tateiwa rock" },
  },
  {
    id: "mikawa-oshima",
    icon: "🏝️",
    ja: { name: "三河大島", area: "豊橋 → 三河安城", hook: "海の向こうに、ぽつんと浮かぶ島。", story: "豊橋を過ぎたあと、A席側に三河湾と三河大島が見えることがあります。大きな観光名所というより、窓の外に一瞬だけ現れる小さな島影。浜名湖のあとにも、海側にはまだ見つける楽しみがあります。見通しがよい日に、海の向こうを探してみてください。" },
    en: { name: "Mikawa Oshima", area: "Toyohashi → Mikawa-Anjo", hook: "A small island beyond the bay.", story: "After Toyohashi, Mikawa Bay and Mikawa Oshima may appear on the Seat A side. It is less a famous landmark than a small island silhouette that quietly rewards a window-seat glance. On a clear day, keep looking across the bay." },
    minutesFromTokyo: 84, side: "A", category: "notable", confidence: "needs-check", durationSec: 45, scene: "bay",
    image: "images/20181213_mikawa_oshima_kawasan3.jpg",
    photoCredit: {
      ja: "かわさん @kawasan3",
      en: "Kawasan @kawasan3",
      url: "https://x.com/kawasan3/status/1072976990150348800",
      note: { ja: "夕暮れにうかぶ三河大島", en: "Mikawa Oshima floating in the evening light." },
    },
    references: [REFERENCES.toyokeizaiMikawa],
    map: { lat: 34.7786, lng: 137.2636, ja: "三河大島", en: "Mikawa Oshima" },
  },
  {
    id: "nichiban-anjo",
    icon: "🟦",
    ja: { name: "セロテープの壁看板", area: "三河安城付近", hook: "巨大なセロテープ看板。", story: "東京から名古屋へ向かう列車では、三河安城の少し手前でE席側にニチバン安城工場の大きな壁看板が見えます。名古屋方面から東京へ向かう場合は、三河安城を出てすぐ。赤、白、青のセロテープ広告が工場の壁いっぱいに現れる、東海道新幹線らしい沿線の発見です。" },
    en: { name: "CELLOTAPE Wall Sign", area: "Around Mikawa-Anjo", hook: "A giant tape sign.", story: "On trains from Tokyo toward Nagoya, the large CELLOTAPE wall sign at the Nichiban Anjo Factory appears on the Seat E side shortly before Mikawa-Anjo. In the opposite direction, look just after Mikawa-Anjo. The huge red, white, and blue sign is not a classic landmark, but once you know it is there, you start looking for it on every ride." },
    minutesFromTokyo: 85, side: "E", category: "curious", confidence: "source-backed", durationSec: 25, scene: "solar",
    image: "images/20250221_nichiban_anjo_letus10.jpg",
    photoCredit: {
      ja: "@letus10 / 新幹線の車窓から",
      en: "@letus10 / Shinkansen window blog",
      url: "https://cotetu.seesaa.net/article/510591087.html",
      note: { ja: "ニチバン安城工場のセロテープの壁看板", en: "CELLOTAPE wall sign at Nichiban Anjo Factory" },
    },
    photos: [
      {
        src: "images/20260629_nichiban_anjo_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見えるセロテープの壁看板", en: "CELLOTAPE Wall Sign at night from the Shinkansen" },
        date: "2026-06-29",
        note: { ja: "夜に浮かぶセロテープ広告", en: "The CELLOTAPE ad glowing at night" },
      },
    ],
    references: [REFERENCES.nichibanBlog],
    map: { lat: 34.972656, lng: 137.058777, ja: "ニチバン 安城工場 セロテープ 壁看板", en: "Nichiban Anjo Factory CELLOTAPE wall sign" },
  },
  {
    id: "nagoya-station-skyline",
    icon: "🏙️",
    ja: { name: "名古屋駅前", area: "名古屋到着直前", hook: "高層ビルの谷を、新幹線で抜ける。", story: "東京から新大阪へ向かう列車では、名古屋に着く少し前から車窓が一気に都市の景色へ切り替わります。高層ビル、駅前の密度、線路の重なり。自然や城とは違うけれど、名古屋到着を知らせる大事な車窓です。" },
    en: { name: "Nagoya Station Skyline", area: "Just before Nagoya", hook: "The train cuts through the city.", story: "On trains from Tokyo toward Shin-Osaka, the window suddenly turns urban just before arriving at Nagoya: high-rise buildings, dense station-front blocks, and layers of tracks. It is not a mountain or a castle, but it is an essential view that signals Nagoya is coming." },
    minutesFromTokyo: 94, side: "E", category: "notable", confidence: "verified", durationSec: 90, scene: "hills",
    image: "images/20260530_nagoya_station_1_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-05-30",
      note: { ja: "ねじれた形のビルはモード学園スパイラルタワーズ", en: "The twisted tower is Mode Gakuen Spiral Towers" },
    },
    photos: [
      {
        src: "images/20260530_nagoya_station_2_michikusa.jpg",
        alt: { ja: "新幹線から見える名古屋駅前の高層ビル", en: "Nagoya Station skyline from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
        note: { ja: "左手がJRセントラルタワーズ、右手が大名古屋ビルヂング", en: "JR Central Towers on the left, Dai Nagoya Building on the right" },
      },
      {
        src: "images/20260530_nagoya_station_3_michikusa.jpg",
        alt: { ja: "新幹線から見える名古屋駅前の都市景観", en: "Urban view around Nagoya Station from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
        note: { ja: "モールが建つ前は名古屋城が合間に見えていた", en: "Before the mall was built, Nagoya Castle could be glimpsed between the buildings" },
      },
      {
        src: "images/20260629_2158_nagoya_station_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見える名古屋駅前", en: "Nagoya Station skyline at night from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-06-29",
        note: { ja: "夜の名古屋到着前、駅前の光が近づく", en: "City lights approach just before arriving at Nagoya at night" },
      },
    ],
    map: { lat: 35.170693, lng: 136.881638, ja: "名古屋駅", en: "Nagoya Station" },
  },
  {
    id: "kirin-beer-factory",
    icon: "🏭",
    ja: { name: "キリンビール工場", area: "名古屋 → 岐阜羽島", hook: "巨大な生ビールが、ずらり。", story: "名古屋を出て庄内川を渡り、枇杷島駅の横を過ぎるころ、E席側にキリンビール名古屋工場の貯蔵タンクが見えてきます。遠目には、巨大な生ビールがずらりと並んでいるよう。線路沿いの産業風景なのに、見つけると少し楽しくなる車窓です。" },
    en: { name: "Kirin Beer Factory", area: "Nagoya → Gifu-Hashima", hook: "Rows of giant beers.", story: "After leaving Nagoya, crossing the Shonai River and passing Biwajima, the Kirin Beer Nagoya Factory appears on the Seat E side. Its storage tanks look like rows of giant draft beers from the train window: an industrial scene that somehow turns into a playful discovery." },
    minutesFromTokyo: 98, side: "E", category: "curious", confidence: "verified", durationSec: 25, scene: "solar",
    image: "images/20250920_kirin_beer_factory_letus10.jpg",
    photoCredit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog", url: "https://cotetu.seesaa.net/article/518214924.html" },
    photos: [
      {
        src: "images/20250920_kirin_beer_factory_2_letus10.jpg",
        alt: { ja: "新幹線のE席側から見えるキリンビール工場の貯蔵タンク", en: "Kirin Beer Factory storage tanks from Seat E" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/518214924.html",
      },
      {
        src: "images/20260530_kirin_beer_factory_michikusa.jpg",
        alt: { ja: "新幹線のE席側から見えるキリンビール工場", en: "Kirin Beer Factory from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
      },
    ],
    references: [REFERENCES.kirinBlog],
    map: { lat: 35.2098489, lng: 136.8501779, ja: "キリンビール 名古屋工場", en: "Kirin Beer Nagoya Factory" },
  },
  {
    id: "kiyosu",
    icon: "🏯",
    ja: { name: "清洲城", area: "名古屋 → 岐阜羽島", hook: "信長の城が、線路のすぐ横に。", story: "名古屋を出て数分、線路のすぐ近くに清洲城があらわれます。織田信長が天下取りを始めた城、そして「清洲会議」の舞台。新幹線がいちばん城に近づく瞬間かもしれません。" },
    en: { name: "Kiyosu Castle", area: "Nagoya → Gifu-Hashima", hook: "Nobunaga's trackside castle.", story: "A few minutes out of Nagoya, Kiyosu Castle appears startlingly close to the line. This is where warlord Oda Nobunaga began his rise to power. It may be the closest the Shinkansen ever gets to a castle." },
    minutesFromTokyo: 99, side: "E", category: "notable", confidence: "verified", durationSec: 12, scene: "castle",
    image: "images/20240719_kiyosu_castle_asami_k920.jpg",
    photoCredit: { ja: "久保井麻美さん @asami_k920", en: "Asami Kuboi @asami_k920", url: "https://x.com/asami_k920/status/1814165589851795710" },
    photos: [
      {
        src: "images/20250309_kiyosu_castle_lightup_asami_k920.jpg",
        timeOfDay: "night",
        alt: { ja: "ライトアップされた清洲城", en: "Illuminated Kiyosu Castle" },
        credit: { ja: "久保井麻美さん @asami_k920", en: "Asami Kuboi @asami_k920" },
        sourceUrl: "https://x.com/asami_k920/status/1898673771084492889",
      },
      {
        src: "images/20260530_kiyosu_castle.jpg",
        alt: { ja: "新幹線のE席側から見える清洲城", en: "Kiyosu Castle from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
      },
    ],
    references: [REFERENCES.kiyosuCastle, REFERENCES.kojodanWindowCastles],
    map: { lat: 35.2165750, lng: 136.8435972, ja: "清洲城", en: "Kiyosu Castle" },
  },
  {
    id: "solar-ark",
    icon: "☀️",
    ja: { name: "ソーラーアーク", area: "名古屋 → 岐阜羽島", hook: "突然、巨大な太陽の船。", story: "名古屋を出て清洲城を過ぎ、岐阜羽島へ近づくころ、E席側に巨大な弧を描くソーラーアークがあらわれます。名所案内には出てきにくいけれど、見つけると忘れにくい沿線の異物感。ロゴの有無など、時期による表情の違いも面白い見どころです。" },
    en: { name: "Solar Ark", area: "Nagoya → Gifu-Hashima", hook: "A giant solar ship, out of nowhere.", story: "After Nagoya and Kiyosu Castle, as the train approaches Gifu-Hashima, the Solar Ark sweeps into view on the Seat E side: a huge dark arc beside the line. It is not a usual guidebook landmark, but it is exactly the kind of strange window-seat find that sticks in memory." },
    minutesFromTokyo: 103, side: "E", category: "curious", confidence: "verified", durationSec: 35, scene: "solar",
    image: "images/20251212_solar_ark_2_letus10.jpg",
    photoCredit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog", url: "https://cotetu.seesaa.net/article/519526266.html" },
    photos: [
      {
        src: "images/20251212_solar_ark_1_letus10.jpg",
        alt: { ja: "新幹線のE席側から見えるソーラーアーク", en: "Solar Ark from Seat E" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/519526266.html",
      },
      {
        src: "images/201707_solar_ark_letus10.jpg",
        alt: { ja: "Panasonicロゴが残っていた頃のソーラーアーク", en: "Solar Ark when the Panasonic logo was still visible" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/519526266.html",
      },
      {
        src: "images/20260530_solar_ark.jpg",
        alt: { ja: "新幹線のE席側から見えるソーラーアーク", en: "Solar Ark from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
      },
    ],
    references: [REFERENCES.solarArkBlog],
    map: { lat: 35.3176417, lng: 136.6832861, ja: "ソーラーアーク", en: "Solar Ark" },
  },
  {
    id: "gifu-castle",
    icon: "🏯",
    ja: { name: "岐阜城", area: "岐阜羽島 → 米原", hook: "山の上に、小さな城。", story: "岐阜羽島を過ぎ、木曽三川を渡る前後で、E席側の遠くに金華山が見えることがあります。その山頂にあるのが岐阜城。線路からは10km以上離れているため、城そのものを見つけるには晴れた日と少しの集中力が必要です。掲載写真は、同じ岐阜城を東海道本線側から捉えた記録です。" },
    en: { name: "Gifu Castle", area: "Gifu-Hashima → Maibara", hook: "A tiny castle on a mountain.", story: "After Gifu-Hashima, around the Kiso Three Rivers, Mt. Kinka may be visible far away on the Seat E side. Gifu Castle sits on its summit. The castle is more than 10 km from the Shinkansen line, so spotting the keep itself takes a clear day and a focused eye. The photo shown here was taken from the Tokaido Main Line as a reference view of the same castle." },
    minutesFromTokyo: 106, side: "E", category: "notable", confidence: "source-backed", durationSec: 120, scene: "castle",
    image: "images/20250927_gifu_castle_letus10.jpg",
    photoCredit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog", url: "https://cotetu.seesaa.net/article/518296647.html" },
    photos: [
      {
        src: "images/20250927_gifu_castle_2_letus10.jpg",
        alt: { ja: "東海道本線側から見た岐阜城", en: "Gifu Castle seen from the Tokaido Main Line side" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/518296647.html",
      },
    ],
    references: [REFERENCES.gifuCastleBlog],
    map: { lat: 35.4339, lng: 136.7824, ja: "岐阜城 金華山", en: "Gifu Castle Mt. Kinka" },
  },
  {
    id: "kinshozan",
    icon: "⛏️",
    ja: { name: "金生山", area: "岐阜羽島 → 米原（大垣付近）", hook: "消えた岐阜のピラミッド。", story: "岐阜羽島を過ぎて大垣へ向かうあたり、E席側に白く削られた山肌が見えます。金生山は石灰岩の山で、かつては「岐阜のピラミッド」と呼ばれた四角錐の山頂部分が車窓から見えました。いま、その山頂部分はもうありません。長年にわたる石灰岩の採掘によって大きく削り取られ、白い岩肌が階段状にむき出しになった独特の景観を形成しています。採掘が景色を変えていくことまで含めて、記憶に残る車窓です。" },
    en: { name: "Mt. Kinsho", area: "Gifu-Hashima → Maibara, near Ogaki", hook: "The vanished Gifu pyramid.", story: "After Gifu-Hashima, near Ogaki, a pale quarried mountainside appears on the Seat E side. Mt. Kinsho is a limestone mountain once known from the train window for a pyramid-like peak nicknamed the 'Gifu Pyramid.' That peak is no longer there. Long years of limestone quarrying have cut deeply into the mountain, leaving white rock faces exposed in stepped layers. The changed landscape itself is part of the story: a mountain reshaped by industry, caught in a few seconds from the Shinkansen." },
    minutesFromTokyo: 106, side: "E", category: "notable", confidence: "verified", durationSec: 45, scene: "mountain",
    image: "images/20260704_kinshozan_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-07-04",
      note: { ja: "のぞみ27号、東京11:12発、13:00撮影", en: "Nozomi 27, departed Tokyo at 11:12, photographed at 13:00." },
    },
    references: [REFERENCES.kinshozanWiki],
    map: { lat: 35.405612, lng: 136.57348, ja: "金生山 大垣", en: "Mt. Kinsho Ogaki" },
  },
  {
    id: "ibuki",
    icon: "⛰️",
    ja: { name: "伊吹山", area: "岐阜羽島 → 米原", hook: "冬は雪をかぶる、関ヶ原の主。", story: "米原の手前、車窓の右手にどっしりと構えるのが伊吹山。古事記にも登場する近江の名山で、冬の雪化粧はみごとです。このあたりは関ヶ原——日本の歴史が動いた土地を、いま時速285kmで駆け抜けています。" },
    en: { name: "Mt. Ibuki", area: "Gifu-Hashima → Maibara", hook: "Sekigahara's snowy mountain.", story: "Before Maibara, Mt. Ibuki rises on the Fuji side — a storied peak that appears in Japan's oldest chronicles, magnificent under winter snow. You're crossing Sekigahara, where the decisive battle of 1600 changed Japanese history. At 285 km/h." },
    minutesFromTokyo: 110, side: "E", category: "classic", confidence: "verified", durationSec: 180, scene: "mountain",
    image: "images/20240114_ibukiyama.png",
    photoCredit: { ja: "michikusa", en: "michikusa", date: "2024-01-14" },
    photos: [
      {
        src: "images/20260530_ibukiyama.jpg",
        alt: { ja: "新幹線のE席側から見える伊吹山", en: "Mt. Ibuki from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
      },
      {
        src: "images/20260530_ibukiyama_2_michikusa.jpg",
        alt: { ja: "新幹線のE席側から見える伊吹山", en: "Mt. Ibuki from Seat E" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-05-30",
      },
    ],
    references: [REFERENCES.ibuki],
    map: { lat: 35.41778, lng: 136.40611, ja: "伊吹山", en: "Mt. Ibuki" },
  },
  {
    id: "nangu-taisha",
    icon: "⛩️",
    ja: { name: "南宮大社", area: "岐阜羽島 → 米原", hook: "田園の向こうに、大鳥居。", story: "東京から新大阪方面へ向かう列車では、岐阜羽島を出て関ヶ原へ向かう途中、A席側の田園の向こうに南宮大社の大鳥居が見えます。新大阪から東京方面へ向かう場合は、米原を出て関ヶ原を越えたあと、岐阜羽島へ向かう途中のA席側です。遠くの社殿を探すというより、赤い鳥居を一瞬で拾う車窓です。" },
    en: { name: "Nangu Taisha Shrine", area: "Gifu-Hashima → Maibara", hook: "A torii beyond the fields.", story: "From Tokyo toward Shin-Osaka, look from Seat A after Gifu-Hashima as the train heads toward Sekigahara. From Shin-Osaka toward Tokyo, look from Seat A after Maibara and Sekigahara, before Gifu-Hashima. The large torii gate of Nangu Taisha Shrine stands beyond the fields: less about seeing the whole shrine than catching a flash of red in the landscape." },
    minutesFromTokyo: 107, side: "A", category: "notable", confidence: "verified", durationSec: 20, scene: "pagoda",
    routeNote: {
      ja: "東京から新大阪方面なら岐阜羽島を出たあと、新大阪から東京方面なら米原を出て関ヶ原を越えたあと、A席側を見てください。",
      en: "Tokyo to Shin-Osaka: watch Seat A after Gifu-Hashima. Shin-Osaka to Tokyo: watch Seat A after Maibara and Sekigahara.",
    },
    image: "images/20260629_nangu_taisha_1_michikusa.jpg",
    photoCredit: {
      ja: "michikusa",
      en: "michikusa",
      date: "2026-06-29",
      note: { ja: "のぞみ99号・A席側、7:40撮影", en: "Nozomi 99, Seat A side, photographed at 7:40." },
    },
    photos: [
      {
        src: "images/20260629_nangu_taisha_2_michikusa.jpg",
        alt: { ja: "新幹線のA席側から見える南宮大社の大鳥居", en: "Nangu Taisha torii gate from Seat A" },
        date: "2026-06-29",
        note: { ja: "田園の向こうに見える大鳥居", en: "The large torii beyond the fields" },
      },
    ],
    references: [REFERENCES.nanguTaisha],
    map: { lat: 35.3611234, lng: 136.5265913, ja: "南宮大社 大鳥居", en: "Nangu Taisha torii gate" },
  },
  {
    id: "sawayama-castle",
    icon: "🏯",
    ja: { name: "佐和山城跡", area: "米原 → 京都", hook: "石田三成の城跡を、田んぼ越しに。", story: "米原を過ぎて少し、E席側に佐和山城跡の山と看板が見えることがあります。佐和山城は、関ヶ原の戦いで敗れた石田三成の居城。天守は残っていませんが、看板を見つけると、関ヶ原から彦根城へ続く歴史の流れが数分の車窓に重なります。" },
    en: { name: "Sawayama Castle Ruins", area: "Maibara → Kyoto", hook: "Mitsunari's hill beyond the fields.", story: "Soon after Maibara, the hill and sign for Sawayama Castle may appear on the Seat E side. This was the castle of Ishida Mitsunari, defeated at Sekigahara. No keep remains, but spotting the sign connects Sekigahara, Sawayama, and Hikone in just a few minutes of window time." },
    minutesFromTokyo: 116, side: "E", category: "notable", confidence: "needs-check", durationSec: 30, scene: "castle",
    image: "images/20240719_sawayama_castle_asami_k920.jpg",
    photoCredit: { ja: "久保井麻美さん @asami_k920", en: "Asami Kuboi @asami_k920", url: "https://x.com/asami_k920/status/1814165589851795710" },
    photos: [
      {
        src: "images/20250831_sawayama_castle_letus10.jpg",
        alt: { ja: "新幹線のE席側から見える佐和山城跡の看板と山", en: "Sawayama Castle Ruins sign and hill from Seat E" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/517840979.html",
      },
    ],
    references: [REFERENCES.sawayamaBlog, REFERENCES.sawayama],
    map: { lat: 35.2840, lng: 136.2770, ja: "佐和山城跡", en: "Sawayama Castle Ruins" },
  },
  {
    id: "hikone-castle",
    icon: "🏯",
    ja: { name: "彦根城", area: "米原 → 京都", hook: "国宝の天守を、街の向こうに。", story: "米原を出たあと、E席側の街並みの向こうに彦根城の天守が小さく見えることがあります。大きくはありません。だからこそ、見つけた瞬間にうれしい。琵琶湖東岸の歴史が、数秒だけ窓の中に入ってきます。" },
    en: { name: "Hikone Castle", area: "Maibara → Kyoto", hook: "A tiny National Treasure keep.", story: "After Maibara, Hikone Castle's keep may appear small beyond the town on the Seat E side. It is not a big, obvious view; that is what makes spotting it satisfying. For a few seconds, the history of eastern Lake Biwa enters the window." },
    minutesFromTokyo: 116, side: "E", category: "notable", confidence: "needs-check", durationSec: 20, scene: "castle",
    image: "images/20240719_hikone_castle_asami_k920.jpg",
    photoCredit: { ja: "久保井麻美さん @asami_k920", en: "Asami Kuboi @asami_k920", url: "https://x.com/asami_k920/status/1814165589851795710" },
    references: [REFERENCES.hikoneCastle],
    map: { lat: 35.2765, lng: 136.2518, ja: "彦根城", en: "Hikone Castle" },
  },
  {
    id: "kannonji-castle",
    icon: "🏯",
    ja: { name: "観音寺城跡", area: "米原 → 京都", hook: "山の稜線に、六角氏の城跡を探す。", story: "安土の近く、E席側の山並みに観音寺城跡が見えることがあります。天守を見るスポットではなく、山城のあった稜線を探す車窓です。近江の平野と山が近づくこの区間で、戦国の地形をそのまま眺める感覚があります。" },
    en: { name: "Kannonji Castle Ruins", area: "Maibara → Kyoto", hook: "A castle ridge in the mountains.", story: "Near Azuchi, the ridge of Kannonji Castle may be visible on the Seat E side. This is not a keep-spotting view; it is about reading the mountain where a Sengoku-period castle once stood. In this stretch, the landscape itself becomes the history." },
    minutesFromTokyo: 120, side: "E", category: "notable", confidence: "needs-check", durationSec: 45, scene: "mountain",
    image: "images/20240719_kannonji_castle_asami_k920.jpg",
    photoCredit: { ja: "久保井麻美さん @asami_k920", en: "Asami Kuboi @asami_k920", url: "https://x.com/asami_k920/status/1814165589851795710" },
    references: [REFERENCES.kannonjiCastle],
    map: { lat: 35.1420, lng: 136.1510, ja: "観音寺城跡", en: "Kannonji Castle Ruins" },
  },
  {
    id: "omi-fuji",
    icon: "⛰️",
    ja: { name: "近江富士", area: "米原 → 京都", hook: "琵琶湖の手前、もうひとつの富士。", story: "米原を出てしばらくすると、A席側に三角の美しい山が見えてきます。三上山、別名・近江富士。水田に映れば、車窓だけの逆さ富士です。少し余裕を持って探してみてください。" },
    en: { name: "Omi Fuji", area: "Maibara → Kyoto", hook: "Another Fuji, before Kyoto.", story: "After Maibara, look from Seat A for Mt. Mikami, nicknamed Omi Fuji for its clean triangular shape. When the fields are wet, it becomes a window-seat reflection: a tiny upside-down Fuji. Start looking a little early." },
    minutesFromTokyo: 123, side: "A", sideLabel: { ja: "A席側", en: "Seat A side" }, category: "notable", confidence: "needs-check", durationSec: 90, scene: "mountain",
    image: "images/20250523_omi_fuji_kawasan3.jpg",
    photoCredit: {
      ja: "かわさん @kawasan3",
      en: "Kawasan @kawasan3",
      url: "https://x.com/kawasan3/status/1925668108024320321",
      note: { ja: "水田に映る逆さ富士", en: "Upside-down Fuji reflected in a rice field" },
    },
    photos: [
      {
        src: "images/20250523_omi_fuji_wheat_kawasan3.jpg",
        alt: { ja: "近江富士の前が小麦色になった景色", en: "Omi Fuji with golden wheat in front" },
        credit: { ja: "かわさん @kawasan3", en: "Kawasan @kawasan3" },
        sourceUrl: "https://x.com/kawasan3/status/1925668834393960462",
        note: { ja: "近江富士の前が小麦色", en: "The land in front of Omi Fuji turns wheat-colored" },
      },
      {
        src: "images/20260629_omi_fuji_michikusa.jpg",
        alt: { ja: "新幹線のA席側から見える近江富士", en: "Omi Fuji from Seat A on the Shinkansen" },
        date: "2026-06-29",
        note: { ja: "田園の向こうの近江富士", en: "Omi Fuji beyond the fields" },
      },
    ],
    references: [REFERENCES.omiFujiPark],
    map: { lat: 35.0479, lng: 136.0450, ja: "三上山 近江富士", en: "Mt. Mikami Omi Fuji" },
  },
  {
    id: "seta-karahashi",
    icon: "🌉",
    ja: { name: "瀬田の唐橋", area: "米原 → 京都", hook: "川に架かる、京の手前の橋。", story: "京都へ近づく少し前、E席側に瀬田川と瀬田の唐橋が見えてきます。日本書紀にも登場する交通の要衝で、古くから「唐橋を制するものは天下を制する」と言われた橋。急がば回れの由来にも重なる、京都目前の一瞬です。" },
    en: { name: "Seta no Karahashi Bridge", area: "Maibara → Kyoto", hook: "A bridge before Kyoto.", story: "A little before Kyoto, Seat E may open onto the Seta River and Seta no Karahashi Bridge. It is an old strategic crossing, even appearing in early Japanese chronicles, and is linked to the idea behind the proverb 'more haste, less speed.' It passes quickly, just before Kyoto." },
    minutesFromTokyo: 127, side: "E", category: "notable", confidence: "source-backed", durationSec: 45, scene: "lake",
    image: "images/20250909_seta_karahashi_c91256633.jpg",
    photoCredit: { ja: "@C91256633", en: "@C91256633", url: "https://x.com/C91256633/status/1965377316537925644" },
    photos: [
      {
        src: "images/20250820_seta_karahashi_letus10.jpg",
        alt: { ja: "晴れた日の瀬田の唐橋", en: "Seta no Karahashi Bridge on a clear day" },
        credit: { ja: "@letus10 / 新幹線の車窓から", en: "@letus10 / Shinkansen window blog" },
        sourceUrl: "https://cotetu.seesaa.net/article/517709224.html",
      },
      {
        src: "images/20260629_2125_seta_karahashi_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見える瀬田の唐橋付近", en: "Around Seta no Karahashi at night from the Shinkansen" },
        credit: { ja: "michikusa", en: "michikusa" },
        date: "2026-06-29",
        note: { ja: "夜の瀬田川を渡る光", en: "Lights crossing the Seta River at night" },
      },
    ],
    references: [REFERENCES.setaKarahashi],
    map: { lat: 34.97306, lng: 135.90611, ja: "瀬田の唐橋", en: "Seta no Karahashi Bridge" },
  },
  {
    id: "toji",
    icon: "⛩️",
    ja: { name: "東寺 五重塔", area: "京都駅 前後", hook: "「京都に来た」が、一瞬でわかる。", story: "京都駅の南側、東寺の五重塔は日本でいちばん高い木造の塔です。1200年前からこの街を見おろしてきた塔が、新幹線の窓から見える——京都の到着を告げる、最高の合図です。" },
    en: { name: "To-ji Pagoda", area: "Around Kyoto Sta.", hook: "One glance, and you know it's Kyoto.", story: "South of Kyoto Station rises the five-story pagoda of To-ji — the tallest wooden tower in Japan, watching over the city for 1,200 years. Catching it from the train window is the perfect announcement: you have arrived in Kyoto." },
    minutesFromTokyo: 131, side: "A", category: "classic", confidence: "verified", durationSec: 40, scene: "pagoda",
    image: "images/20260510_toji.png",
    photoCredit: { ja: "michikusa", en: "michikusa", date: "2026-05-10" },
    references: [REFERENCES.toji],
    map: { lat: 34.980361, lng: 135.747694, ja: "東寺 五重塔", en: "To-ji Pagoda Kyoto" },
  },
  {
    id: "torikai-train-depot",
    icon: "🚄",
    ja: { name: "鳥飼車両基地", area: "京都 → 新大阪", hook: "白い列車が、ずらり。", story: "新大阪に近づくころ、E席側に新幹線が並ぶ大きな車両基地が広がります。走ってきた列車の裏側、整備と待機の場所。名所というより、旅を支える現場が突然ひらける車窓です。見える範囲が広いので、少し長めに探してください。" },
    en: { name: "Torikai Train Depot", area: "Kyoto → Shin-Osaka", hook: "Rows of Shinkansen at rest.", story: "As you approach Shin-Osaka, Seat E may open onto a vast Shinkansen depot: rows of white trains resting beside the line. It is not a classic landmark; it is the backstage of the journey, where the trains wait and are cared for. The view stretches for a while, so keep looking." },
    minutesFromTokyo: 141, side: "E", category: "curious", confidence: "source-backed", durationSec: 240, scene: "hills",
    image: "images/20260614_torikai_train_depot_yamato160.jpg",
    photoCredit: { ja: "@yamato160", en: "@yamato160", url: "https://x.com/yamato160/status/2066003172884365364" },
    photos: [
      {
        src: "images/20260629_torikai_train_depot_michikusa.jpg",
        alt: { ja: "新幹線から見える鳥飼車両基地", en: "Torikai Train Depot from the Shinkansen" },
        date: "2026-06-29",
        note: { ja: "白い列車がずらり", en: "Rows of white trains" },
      },
      {
        src: "images/20260629_torikai_train_depot_night_michikusa.jpg",
        timeOfDay: "night",
        alt: { ja: "夜の新幹線から見える鳥飼車両基地", en: "Torikai Train Depot at night from the Shinkansen" },
        date: "2026-06-29",
        note: { ja: "夜に眠る新幹線たち", en: "Shinkansen sleeping at night" },
      },
    ],
    references: [REFERENCES.tokaidoShinkansen],
    map: { lat: 34.77598, lng: 135.5704782, ja: "鳥飼車両基地", en: "Torikai Train Depot" },
  },
];
